name: BDD Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        # use a known build environment
        container: python:3.8-slim

        # Required services
        services:
            # Label used to access the service container
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres  # modified
                ports:
                    - 5432:5432
                # Set health checks to wait until postgres has started
                options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5

        # Steps for the build
        steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run the server locally
        run: |
          echo "\n*** STARTING APPLICATION ***\n"
          honcho start &
          sleep 5
          curl -I http://localhost:5000/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: "postgres://postgres:postgres@postgres:5432/postgres"

      - name: Run unit tests with behave
        run: behave