name: BDD Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8-slim

    services:
      couchdb:
        image: couchdb:latest
        ports:
          - 5984:5984
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: pass
        options: >-
          --health-cmd "curl -X GET http://couchdb:5984/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run the server locally
        run: |
          echo "\n*** CREATING TEST DB ***\n"
          curl -X PUT http://admin:pass@couchdb:5984/test
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=critical --bind=0.0.0.0:5000 services:app &
          sleep 5
          curl -I http://localhost:5000/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          BINDING_CLOUDANT: '{"username":"admin","password":"pass","host":"couchdb","port":5984,"url":"http://admin:pass@couchdb:5984"}'

      - name: Run unit tests with behave
        run: behave